import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Witenconsulting</title>
        <meta name="description" content="Generated by Witenconsulting" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <h2>
            Entrega recepcion SIER <span>-&gt;</span>
          </h2>
        </div>

        <div className={styles.grid}>
        </div>
      </main>
    </>
  );
}
